import AstronomicalBody from "./interfaces/AstronomicalBody";

const astronomicalBodies: AstronomicalBody[] = [
  {
    id: "sun",
    scale: 3,
    rotationSpeed: 0.01,
    orbitingSpeed: 0,
    position: [0, 0, 0],
    color: "Orange",
    isLightSource: true,
    title: "The Sun",
    wikipediaPageId: 26751,
  },
  {
    id: "mercury",
    scale: 0.6,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.01,
    position: [9, 0, 0],
    color: "Brown",
    title: "Mercury",
    wikipediaPageId: 19694,
  },
  {
    id: "venus",
    scale: 0.7,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.003,
    position: [12, 0, 0],
    color: "Khaki",
    title: "Venus",
    wikipediaPageId: 32745,
  },
  {
    id: "earth",
    scale: 1,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.008,
    position: [16, 0, 0],
    color: "SkyBlue",
    title: "Earth",
    wikipediaPageId: 9228,
  },
  {
    id: "mars",
    scale: 0.8,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.01,
    position: [19, 0, 0],
    color: "DarkRed",
    title: "Mars",
    wikipediaPageId: 14640471,
  },
  {
    id: "jupiter",
    scale: 1.6,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.004,
    position: [24, 0, 0],
    color: "LightSalmon",
    title: "Jupiter",
    wikipediaPageId: 38930,
  },
  {
    id: "saturn",
    scale: 1.4,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.002,
    position: [29, 0, 0],
    color: "Bisque",
    title: "Saturn",
    wikipediaPageId: 44474,
  },
  {
    id: "uranus",
    scale: 1.2,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.009,
    position: [34, 0, 0],
    color: "Green",
    title: "Uranus",
    wikipediaPageId: 44475,
  },
  {
    id: "neptune",
    scale: 1.3,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.01,
    position: [39, 0, 0],
    color: "Blue",
    title: "Neptune",
    wikipediaPageId: 19003265,
  },
  {
    id: "pluto",
    scale: 0.4,
    rotationSpeed: 0.01,
    orbitingSpeed: 0.001,
    position: [47, 0, 0],
    color: "RebeccaPurple",
    title: "Pluto",
    wikipediaPageId: 44469,
  },
];

export default astronomicalBodies;
